project_id = "mhmwzlzccxjsihqalrau"

[functions.register-partner]
verify_jwt = false

[functions.fetch-crif-report]
verify_jwt = false

[functions.fetch-cibil-report]
verify_jwt = false

[functions.fetch-experian-report]
verify_jwt = false

[functions.fetch-equifax-report]
verify_jwt = false
